# Dockerfile for excel-upload-service
# Generated by Copilot based on spec-driven instructions

FROM python:3.10-slim

LABEL maintainer="shantam123000@gmail.com"

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy application code
COPY app.py ./
COPY specs/ ./specs/

# Expose port (if applicable)
EXPOSE 8080

# Default command
CMD ["python", "app.py"]
