# test_app.py - Sample unit tests for excel-upload-service
# Generated by Copilot

import unittest
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.dirname(os.path.dirname(__file__))))
from app import app


class TestApp(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()

    def test_health_endpoint(self):
        response = self.client.get("/health")
        self.assertEqual(response.status_code, 200)
        self.assertIn(b"healthy", response.data)


if __name__ == "__main__":
    unittest.main()
