# Terraform AWS ECS Webapp Module Skeleton
# Generated by Copilot based on spec-driven instructions

terraform {
  required_version = ">= 1.0.0"
  backend "s3" {
    bucket = "my-terraform-backend"
    key    = "excel-upload-service/terraform.tfstate"
    region = "ap-south-1"
  }
}

module "ecs_webapp" {
  source  = "git::https://github.com/my-org/terraform-modules.git//ecs-webapp?ref=v1.3.0"
  # Add required variables here
}
