# Outputs for AWS ECS Webapp Module
# Generated by Copilot

output "service_arn" {
  description = "ARN of the ECS service"
  value       = module.ecs_webapp.service_arn
}

output "task_definition_arn" {
  description = "ARN of the ECS task definition"
  value       = module.ecs_webapp.task_definition_arn
}
