# Variables for AWS ECS Webapp Module
# Generated by Copilot

variable "service_name" {
  description = "Name of the ECS service"
  type        = string
}

variable "image_url" {
  description = "Docker image URL for deployment"
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, stage, prod)"
  type        = string
}
