#!/usr/bin/env bash
# healthcheck.sh - Simple health check script for excel-upload-service
# Generated by Copilot

set -e

URL="${1:-http://localhost:8080/health}"
RETRIES=3
TIMEOUT=120

for i in $(seq 1 $RETRIES); do
  echo "Attempt $i: Checking health at $URL..."
  if curl --max-time $TIMEOUT --fail "$URL"; then
    echo "Healthcheck passed."
    exit 0
  fi
  sleep 5
done

echo "Healthcheck failed after $RETRIES attempts."
exit 1
